version: '3'

services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "9229:9229"
      
  postgres:
    image: debezium/postgres:9.6
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=hypechat
    - POSTGRES_PASSWORD=hypechat
    - POSTGRES_DB=hypechat
